services:
  postgres:
    image: postgres:latest
    container_name: logistics-api
    environment:
      POSTGRES_DB: ${DEV_DB_NAME}
      POSTGRES_USER: ${DEV_DB_USERNAME}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      TZ: "UTC-4"
    ports:
      - 5433:5432
    command: -p 5432
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: logistics-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEV_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEV_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_DEV_PORT}
    ports:
      - 4848:4848
    depends_on:
      - postgres
    env_file:
      - .env
